version: '3'

services:
  main-app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/home/node/app
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=picpay
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local